# Generated by Django 4.2.1 on 2023-07-28 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='num_document',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{8,10}$', 'El número de documento debe tener entre 8 y 10 dígitos.')]),
        ),
    ]
