# Generated by Django 4.2.1 on 2023-07-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientoD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
