# Generated by Django 4.2.1 on 2023-07-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientoD', '0002_remove_athlete_at_user_athlete_at_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anthropometric',
            name='atpt_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
