# Generated by Django 4.2.1 on 2023-07-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientoD', '0003_alter_anthropometric_atpt_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anthropometric',
            name='atpt_updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
