# Generated by Django 4.2.1 on 2023-07-19 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientoD', '0005_remove_anthropometric_atpt_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnthropometricHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atpt_controlDate', models.DateField(auto_now_add=True, verbose_name='Fecha de Control')),
                ('atpt_arm', models.IntegerField(verbose_name='Brazo')),
                ('atpt_chest', models.CharField(max_length=45, verbose_name='Pecho')),
                ('atpt_hip', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Cadera')),
                ('atpt_calf', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Gemelo')),
                ('atpt_humerus', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Húmero')),
                ('atpt_femur', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Fémur')),
                ('atpt_wrist', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Muñeca')),
                ('atpt_triceps', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Tríceps')),
                ('atpt_suprailiac', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Supraespinal')),
                ('atpt_pectoral', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Pectoral')),
                ('atpt_height', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Talla')),
                ('atpt_weight', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Peso')),
                ('atpt_bmi', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='IMC')),
                ('atpt_updated_date', models.DateTimeField(auto_now=True)),
                ('anthropometric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientoD.anthropometric', verbose_name='Antropométrica')),
            ],
        ),
    ]
