# Generated by Django 4.2.1 on 2023-07-19 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientoD', '0006_anthropometrichistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anthropometric',
            options={'ordering': ['id'], 'verbose_name': 'Antropométrica', 'verbose_name_plural': 'Antropométricas'},
        ),
        migrations.AlterModelOptions(
            name='athlete',
            options={'ordering': ['id'], 'verbose_name': 'Atleta', 'verbose_name_plural': 'Atletas'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='positions',
            options={'ordering': ['id'], 'verbose_name': 'Posición', 'verbose_name_plural': 'Posiciones'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['id'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
    ]
