# Generated by Django 4.2.1 on 2023-07-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergie_name', models.CharField(max_length=45)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'allergies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Anthropometric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atpt_controldate', models.DateField(db_column='atpt_controlDate')),
                ('atpt_arm', models.IntegerField()),
                ('atpt_chest', models.CharField(max_length=45)),
                ('atpt_hip', models.IntegerField()),
                ('atpt_calf', models.IntegerField()),
                ('atpt_humerus', models.IntegerField()),
                ('atpt_femur', models.IntegerField()),
                ('atpt_wrist', models.IntegerField()),
                ('atpt_triceps', models.IntegerField()),
                ('atpt_suprailiac', models.IntegerField()),
                ('atpt_pectoral', models.IntegerField()),
                ('atpt_height', models.IntegerField()),
                ('atpt_weight', models.IntegerField()),
                ('atpt_bmi', models.IntegerField()),
                ('atpt_updated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'anthropometric',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_technicalv', models.CharField(max_length=50)),
                ('at_tacticalv', models.CharField(max_length=50)),
                ('at_physicalv', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'athlete',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AthleteTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorsal', models.IntegerField()),
                ('positions_initial', models.CharField(max_length=45)),
                ('position_alternative', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'athlete_team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=11)),
                ('c_name', models.CharField(max_length=30)),
                ('date_create_category', models.DateTimeField(auto_now_add=True, db_column='date_create_Category')),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_name', models.CharField(max_length=45)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'disabilities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField()),
            ],
            options={
                'db_table': 'instructors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=230)),
                ('photo_user', models.ImageField(blank=True, max_length=255, upload_to='media/')),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(max_length=9)),
                ('telephone_number', models.CharField(max_length=10)),
                ('date_create', models.DateField()),
                ('type_document_id', models.CharField(max_length=20)),
                ('num_document', models.IntegerField()),
                ('file', models.FileField(blank=True, upload_to='media/')),
                ('file_v', models.FileField(blank=True, upload_to='media/')),
                ('file_f', models.FileField(blank=True, upload_to='media/')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_instructors', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'people',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgrammingTournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('position', models.IntegerField()),
                ('matches_played', models.IntegerField()),
                ('win', models.IntegerField()),
                ('lose', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('penalty_score', models.IntegerField()),
                ('registration_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'programming_tournaments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReceiptPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_day', models.DateField()),
                ('full_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'receipt_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rol', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=40)),
                ('service_status', models.IntegerField()),
                ('description', models.TextField()),
                ('service_value', models.DecimalField(decimal_places=0, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('sport_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'sports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create_team', models.DateTimeField(auto_created=True, db_column='date_create_Team')),
                ('team_name', models.CharField(max_length=40)),
                ('team_image', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tournament', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('tournament_type', models.CharField(max_length=10)),
                ('max_teams', models.IntegerField()),
                ('max_participants_per_ethlete', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('prize', models.CharField(max_length=100)),
                ('registration_fee', models.DecimalField(decimal_places=0, max_digits=10)),
                ('enrollment_status', models.IntegerField()),
            ],
            options={
                'db_table': 'tournaments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
