# Generated by Django 4.2.1 on 2023-08-04 20:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('g_Deportiva', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='at_physicalv',
            new_name='physicalv',
        ),
        migrations.RenameField(
            model_name='athlete',
            old_name='at_tacticalv',
            new_name='tacticalv',
        ),
        migrations.RenameField(
            model_name='athlete',
            old_name='at_technicalv',
            new_name='technicalv',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='c_name',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='programmingtournaments',
            name='status',
        ),
        migrations.AddField(
            model_name='programmingtournaments',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='anthropometric',
            name='controlDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='athlete_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='allergies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='g_Deportiva.allergies'),
        ),
        migrations.AlterField(
            model_name='people',
            name='date_create',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='disabilities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='g_Deportiva.disabilities'),
        ),
        migrations.AlterField(
            model_name='people',
            name='file_documentidentity',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='people',
            name='file_f',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='people',
            name='file_v',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='people',
            name='is_instructors',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='people',
            name='photo_user',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='sports',
            name='sport_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='g_Deportiva.people'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='g_Deportiva.rol'),
        ),
    ]
