# Generated by Django 4.2.1 on 2023-08-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g_Deportiva', '0002_rename_at_physicalv_athlete_physicalv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='is_instructors',
        ),
    ]
