# Generated by Django 4.2.1 on 2023-08-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_Deportiva', '0003_remove_people_is_instructors'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
