# Generated by Django 4.2.1 on 2023-08-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_Deportiva', '0004_specialconditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sport',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='descripcion', max_length=250),
            preserve_default=False,
        ),
    ]
