# Generated by Django 4.2.1 on 2023-08-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_Deportiva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='file_documentidentity',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='people',
            name='file_f',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='people',
            name='file_v',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='people',
            name='photo_user',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
