# Generated by Django 4.2.1 on 2023-08-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_Deportiva', '0002_alter_people_file_documentidentity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmingtournaments',
            name='status',
        ),
        migrations.AddField(
            model_name='programmingtournaments',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='athlete_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sports',
            name='sport_status',
            field=models.BooleanField(default=True),
        ),
    ]
