# Generated by Django 4.2.1 on 2023-08-01 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('g_Deportiva', '0004_user_last_login_alter_people_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='allergies',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='g_Deportiva.allergies'),
        ),
        migrations.AlterField(
            model_name='people',
            name='disabilities',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='g_Deportiva.disabilities'),
        ),
    ]
