# Generated by Django 4.2.1 on 2023-08-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_Deportiva', '0006_alter_people_allergies_alter_people_disabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
