# Generated by Django 4.2.1 on 2023-08-02 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g_Deportiva', '0007_alter_team_team_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='c_name',
            new_name='category_name',
        ),
    ]
