# Generated by Django 4.2.1 on 2023-08-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g_Deportiva', '0008_rename_c_name_category_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='at_physicalv',
            new_name='physicalv',
        ),
        migrations.RenameField(
            model_name='athlete',
            old_name='at_tacticalv',
            new_name='tacticalv',
        ),
        migrations.RenameField(
            model_name='athlete',
            old_name='at_technicalv',
            new_name='technicalv',
        ),
    ]
