# Generated by Django 4.2.1 on 2023-08-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_Deportiva', '0009_rename_at_physicalv_athlete_physicalv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='is_instructors',
            field=models.BooleanField(default=False),
        ),
    ]
