# Generated by Django 4.2.1 on 2023-08-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g_Deportiva', '0011_alter_anthropometric_controldate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='is_instructors',
        ),
    ]
